- notebooks/HCPyToolsExample1.ipynb
* added missing import random
* Minor copy  editing and markdown formatting of comment cells
* fixed broken path to example csv file
* removed redundant print functions for nicer pandas table outputs
* fixed incorrect column names for sample data on type changing and predictedcol
* fixed typo in random_forest call
> Fixed bugs in example jupyter notebook preventing full functionality

- CHANGELOG.md
> 252 #resolve

- README.md
* updated readme w/ release process including read the docs details
> 273 resolve

- healthcareai/common/feature_availability_profiler.py
* changed a few print stamements to use dynamic column names
* minor linting.
* added docstrings
> * found bug during R port process where a column was hard coded

- healthcareai/common/model_eval.py
- healthcareai/develop_supervised_model.py
> fixed bug in model_eval.py

- TODO
> deleted the TODO file

- Example2.py
- docs/deploy.md
- healthcareai/deploy_supervised_model.py
- healthcareai/tests/test_deploy_supervised_model_class.py
- healthcareai/tests/test_dev_supervised_model_class.py
- healthcareai/tests/test_model_eval_helpers.py
- notebooks/Example1.ipynb
* added healthcareaiError
* made the db table validation a method
* renamed a bunch of variables for clarity
* ... which required updating the docs and examples
* moved column name logic to instance variable
* turns out we had an extra dataframe copy laying around (creating but never using the instance variable)
* wrote a few tests for the extracted function
> extract db write validation and unittest

- .gitignore
- healthcareai/common/model_eval.py
- healthcareai/develop_supervised_model.py
- healthcareai/simple_mode.py
* some linting
* lots of documentation strings now that things are beginning to settle
* deprecated knn_stats (prototype)
* added simple and advanced random forest regressor
* filled out simple and advanced random forest classifier
* adjusted all advanced (except the to be deprecated ones) to return the algorithm once it has been fit
* renamed SGD classifier
* removed some prototype commented code chunks
* refactored all simple methods for consistency - using a helper method that prints out the appropriate metrics
* updated gitignore to ignore yet more virtualenvs
> Advanced return fit estimators. Simples print metrics. Implement consistency of simple interface.

- docs/profiling_your_data.md
- mkdocs.yml
> * Added documentation for feature_availability_profiler.

- healthcareai/common/model_eval.py
running example_simple_classification.py will illustrate
> * PR AUC is now returned for classifiers

- example_simple_classification.py
- healthcareai/common/model_eval.py
- healthcareai/develop_supervised_model.py
- healthcareai/tests/test_dev_supervised_model_class.py
- healthcareai/tests/test_simple_develop_supervised.py
- healthcareai/tests/test_supervised_model_trainer.py
- healthcareai/tests/test_trained_supervised_model.py
- healthcareai/trained_models/trained_supervised_model.py
- healthcareai/trainer.py
Note there are some known issues (coloring is broken, legend is missing) that are represented in #237 that will be fixed later in effort to keep PRs reasonable and prioritize work.
> ROC plotter works with any number of trained models

- healthcareai/develop_supervised_model.py
> * removed attributes from the constructor (more to follow in #205)

- healthcareai/common/model_eval.py
> * legend fixed - easy PR!

- healthcareai/common/model_eval.py
- healthcareai/develop_supervised_model.py
- healthcareai/trained_models/trained_supervised_model.py
- healthcareai/trainer.py
> Hyperparameters for meta estimators available on TSM and returned in simple trainer

- README.md
> Fix issue #182

- README.md
Two appveyor status are included, and the second one is broken.
> Fixed broken appveyor status

- docs/deploy.md
- docs/getting_started.md
- docs/hints.md
- docs/training.md
- example_advanced.py
- example_classification_1.py
- example_classification_2.py
- example_regression_1.py
- example_regression_2.py
- healthcareai/__init__.py
- healthcareai/common/csv_loader.py
- healthcareai/tests/test_csv_loader.py
- healthcareai/tests/test_trainer.py
* new top level load_csv function with a single error test
* changed all example files to use this function as a data option
*  updated all documentation to use this function
* simplified imports on examples by changing the main __init__,py
> Examples & docs now show how to load your own CSV

- README.md
Resolves #335 and updates the Getting Started section of the README to provide clearer instructions on how to use the project.
> 335 Update Getting Started in README

- .landscape.yml
> Landscape.yml fix

- CHANGELOG.md
- docs/getting_started.md
- example_advanced.py
- healthcareai/common/filters.py
- healthcareai/common/model_eval.py
- healthcareai/supervised_model_trainer.py
- healthcareai/tests/test_dataframe_filters.py
- healthcareai/tests/test_trainer.py
- healthcareai/trained_models/trained_supervised_model.py
> RF feature importance PR #298

- example_advanced.py
- healthcareai/advanced_supvervised_model_trainer.py
- healthcareai/common/categorical_levels.py
- healthcareai/common/database_writers.py
- healthcareai/common/filters.py
- healthcareai/common/get_categorical_levels.py
- healthcareai/common/transformers.py
- healthcareai/common/validators.py
- healthcareai/pipelines/data_preparation.py
- healthcareai/supervised_model_trainer.py
- healthcareai/tests/test_advanced_trainer.py
- healthcareai/tests/test_advanced_trainer_multiclass.py
- healthcareai/tests/test_categorical_levels.py
- healthcareai/tests/test_dataframe_filters.py
- healthcareai/tests/test_dataframe_transformers.py
- healthcareai/tests/test_get_categorical_column_info.py
- healthcareai/tests/test_trained_supervised_model.py
- healthcareai/tests/test_trainer.py
- healthcareai/trained_models/trained_supervised_model.py
* missed scoring metric for logistic regression
* updated some mathematician name spelling
* factored down the prepare_and_subset into tested functions
* removed error from is_binary_classification
> WIP DO NOT MERGE - for diffing only

- healthcareai/common/model_eval.py
- healthcareai/tests/test_model_eval.py
I've run this through 1000 trainings and the non-deterministic sorting issue is gone.
> Confusion matrix: sorting class labels alphabetically

- CHANGELOG.md
- healthcareai/advanced_supvervised_model_trainer.py
- healthcareai/common/helpers.py
- healthcareai/common/transformers.py
- healthcareai/pipelines/data_preparation.py
- healthcareai/tests/helpers.py
- healthcareai/tests/test_advanced_trainer.py
- healthcareai/tests/test_advanced_trainer_multiclass.py
- healthcareai/tests/test_dataframe_transformers.py
- healthcareai/tests/test_feature_availability_profiler.py
- healthcareai/tests/test_trained_supervised_model.py
- healthcareai/tests/test_trainer.py
- healthcareai/trained_models/trained_supervised_model.py
this is a branch from 431, so be sure to merge AFTER that PR.
> Merge Third - tests 300+% faster

- healthcareai/trained_models/trained_supervised_model.py
Change needed in both make_predictions and make_factors.
> Grain column vector must exist in order to add it to results.

- healthcareai/advanced_supvervised_model_trainer.py
- healthcareai/supervised_model_trainer.py
- healthcareai/tests/test_advanced_trainer.py
Pipeline must be passed into AdvancedSupervisedModeTrainer in order for it to be accessible from the saved model on prediction.
> DanWellisch-passinpipeline-448

- healthcareai/common/top_factors.py
- healthcareai/common/transformers.py
fix breakages due to breaking changes in latest pandas
> Sameer Mahajan 473
